// Auto-generated by tools/build_manifest.py — do not hand-edit.
const MANIFEST = [
  {
    "path": "00-start-here/how-to-use-this-guide.md",
    "title": "How to Use This Guide"
  },
  {
    "path": "00-start-here/scrum-master-career-path.md",
    "title": "The Scrum Master Career Path"
  },
  {
    "path": "01-agile-foundations/agile-manifesto.md",
    "title": "The Agile Manifesto"
  },
  {
    "path": "01-agile-foundations/agile-vs-waterfall.md",
    "title": "Agile vs. Waterfall"
  },
  {
    "path": "01-agile-foundations/empiricism-and-lean-thinking.md",
    "title": "Empiricism and Lean Thinking"
  },
  {
    "path": "01-agile-foundations/history-of-scrum.md",
    "title": "The History of Scrum"
  },
  {
    "path": "02-scrum-framework/scrum-values.md",
    "title": "Scrum Values"
  },
  {
    "path": "02-scrum-framework/scrum-theory-pillars.md",
    "title": "Scrum Theory: The Three Pillars"
  },
  {
    "path": "02-scrum-framework/scrum-team.md",
    "title": "The Scrum Team"
  },
  {
    "path": "02-scrum-framework/sprint.md",
    "title": "The Sprint"
  },
  {
    "path": "02-scrum-framework/sprint-planning.md",
    "title": "Sprint Planning"
  },
  {
    "path": "02-scrum-framework/daily-scrum.md",
    "title": "Daily Scrum"
  },
  {
    "path": "02-scrum-framework/sprint-review.md",
    "title": "Sprint Review"
  },
  {
    "path": "02-scrum-framework/sprint-retrospective.md",
    "title": "Sprint Retrospective"
  },
  {
    "path": "02-scrum-framework/product-backlog.md",
    "title": "The Product Backlog"
  },
  {
    "path": "02-scrum-framework/sprint-backlog.md",
    "title": "The Sprint Backlog"
  },
  {
    "path": "02-scrum-framework/increment.md",
    "title": "The Increment"
  },
  {
    "path": "02-scrum-framework/definition-of-done.md",
    "title": "Definition of Done"
  },
  {
    "path": "03-professional-scrum-competencies/00-overview.md",
    "title": "Professional Scrum Competencies: The Skill Behind the Framework"
  },
  {
    "path": "03-professional-scrum-competencies/01-understanding-and-applying-scrum-framework.md",
    "title": "Understanding and Applying the Scrum Framework"
  },
  {
    "path": "03-professional-scrum-competencies/02-developing-people-and-teams.md",
    "title": "Developing People and Teams"
  },
  {
    "path": "03-professional-scrum-competencies/03-managing-products-with-agility.md",
    "title": "Managing Products with Agility"
  },
  {
    "path": "03-professional-scrum-competencies/04-developing-and-delivering-products-professionally.md",
    "title": "Developing and Delivering Products Professionally"
  },
  {
    "path": "03-professional-scrum-competencies/05-evolving-the-agile-organization.md",
    "title": "Evolving the Agile Organization"
  },
  {
    "path": "03-professional-scrum-competencies/06-optimizing-flow.md",
    "title": "Optimizing Flow"
  },
  {
    "path": "04-scrum-master-role/servant-leadership.md",
    "title": "Servant Leadership"
  },
  {
    "path": "04-scrum-master-role/the-4-sm-service-areas.md",
    "title": "The Scrum Master's Service Areas (3 in the Guide, Often Taught as \"4\")"
  },
  {
    "path": "04-scrum-master-role/facilitation-techniques.md",
    "title": "Facilitation Techniques"
  },
  {
    "path": "04-scrum-master-role/coaching-vs-mentoring-vs-teaching.md",
    "title": "Coaching vs. Mentoring vs. Teaching"
  },
  {
    "path": "04-scrum-master-role/conflict-resolution.md",
    "title": "Conflict Resolution"
  },
  {
    "path": "04-scrum-master-role/removing-impediments.md",
    "title": "Removing Impediments"
  },
  {
    "path": "04-scrum-master-role/shielding-vs-enabling.md",
    "title": "Shielding vs. Enabling"
  },
  {
    "path": "04-scrum-master-role/metrics-and-forecasting.md",
    "title": "Metrics and Forecasting"
  },
  {
    "path": "04-scrum-master-role/working-with-difficult-stakeholders.md",
    "title": "Working with Difficult Stakeholders"
  },
  {
    "path": "04-scrum-master-role/anti-patterns-and-scrum-smells.md",
    "title": "Anti-Patterns and Scrum Smells"
  },
  {
    "path": "05-scaling-frameworks/why-and-when-to-scale.md",
    "title": "Why and When to Scale"
  },
  {
    "path": "05-scaling-frameworks/nexus.md",
    "title": "Nexus"
  },
  {
    "path": "05-scaling-frameworks/scrum-at-scale.md",
    "title": "Scrum@Scale"
  },
  {
    "path": "05-scaling-frameworks/less.md",
    "title": "LeSS (Large-Scale Scrum)"
  },
  {
    "path": "05-scaling-frameworks/safe-overview.md",
    "title": "SAFe (Scaled Agile Framework) — Overview"
  },
  {
    "path": "06-real-life-scenarios/00-how-to-use-these-scenarios.md",
    "title": "How to Use These Scenarios"
  },
  {
    "path": "06-real-life-scenarios/01-team-missing-every-sprint-goal.md",
    "title": "The Team Keeps Missing Its Sprint Goal"
  },
  {
    "path": "06-real-life-scenarios/02-product-owner-wont-prioritize.md",
    "title": "The Product Owner Won't Prioritize"
  },
  {
    "path": "06-real-life-scenarios/03-daily-scrum-becomes-status-report-to-manager.md",
    "title": "Daily Scrum Becomes a Status Report to the Manager"
  },
  {
    "path": "06-real-life-scenarios/04-stakeholder-demands-mid-sprint-scope-change.md",
    "title": "A Stakeholder Demands a Mid-Sprint Scope Change"
  },
  {
    "path": "06-real-life-scenarios/05-distributed-team-across-timezones.md",
    "title": "A Distributed Team Across Timezones"
  },
  {
    "path": "06-real-life-scenarios/06-technical-debt-vs-sprint-commitments.md",
    "title": "Technical Debt vs. Sprint Commitments"
  },
  {
    "path": "06-real-life-scenarios/07-retro-that-never-changes-anything.md",
    "title": "The Retro That Never Changes Anything"
  },
  {
    "path": "06-real-life-scenarios/08-scaling-from-one-team-to-five.md",
    "title": "Scaling From One Team to Five"
  },
  {
    "path": "06-real-life-scenarios/09-manager-assigns-tasks-to-individuals.md",
    "title": "A Manager Assigns Tasks to Individuals"
  },
  {
    "path": "06-real-life-scenarios/10-team-conflict-between-two-senior-devs.md",
    "title": "Team Conflict Between Two Senior Developers"
  },
  {
    "path": "06-real-life-scenarios/11-fake-agile-scrumbut-organization.md",
    "title": "\"We Do Scrum Here\" — When the Titles Changed and Nothing Else Did"
  },
  {
    "path": "06-real-life-scenarios/12-underperforming-team-member.md",
    "title": "The Developer Who Isn't Keeping Up"
  },
  {
    "path": "06-real-life-scenarios/13-sprint-review-nobody-attends.md",
    "title": "When Stakeholders Stop Showing Up to Sprint Review"
  },
  {
    "path": "06-real-life-scenarios/14-po-not-available-for-the-team.md",
    "title": "The Product Owner Who's Never in the Room"
  },
  {
    "path": "06-real-life-scenarios/15-velocity-used-to-compare-teams.md",
    "title": "The Cross-Team Velocity Leaderboard"
  },
  {
    "path": "06-real-life-scenarios/16-new-scrum-master-first-30-days.md",
    "title": "A New Scrum Master's First 30 Days"
  },
  {
    "path": "06-real-life-scenarios/17-team-wants-to-abandon-scrum.md",
    "title": "The Team Wants to Drop Scrum Entirely"
  },
  {
    "path": "06-real-life-scenarios/18-handling-a-failed-sprint.md",
    "title": "When the Sprint Goal Becomes Obsolete Mid-Sprint"
  },
  {
    "path": "06-real-life-scenarios/19-remote-facilitation-and-engagement.md",
    "title": "Cameras Off, Nobody Talking: Facilitating a Disengaged Remote Team"
  },
  {
    "path": "06-real-life-scenarios/20-coaching-a-new-product-owner.md",
    "title": "Coaching a Product Owner Who Doesn't Trust Their Own Authority"
  },
  {
    "path": "07-certifications/00-which-certification-should-i-get.md",
    "title": "Which Certification Should I Get?"
  },
  {
    "path": "07-certifications/comparison-table.md",
    "title": "Certification Comparison Table"
  },
  {
    "path": "07-certifications/scrum-org/psm-i.md",
    "title": "PSM I — Professional Scrum Master I"
  },
  {
    "path": "07-certifications/scrum-org/psm-ii.md",
    "title": "PSM II — Professional Scrum Master II"
  },
  {
    "path": "07-certifications/scrum-org/psm-iii.md",
    "title": "PSM III — Professional Scrum Master III"
  },
  {
    "path": "07-certifications/scrum-org/psm-practice-questions.md",
    "title": "PSM Practice Questions"
  },
  {
    "path": "07-certifications/scrum-alliance/csm.md",
    "title": "Certified ScrumMaster (CSM)"
  },
  {
    "path": "07-certifications/scrum-alliance/a-csm.md",
    "title": "Advanced Certified ScrumMaster (A-CSM)"
  },
  {
    "path": "07-certifications/scrum-alliance/csp-sm.md",
    "title": "Certified Scrum Professional - ScrumMaster (CSP-SM)"
  },
  {
    "path": "07-certifications/safe/safe-scrum-master.md",
    "title": "SAFe Scrum Master (SSM)"
  },
  {
    "path": "07-certifications/safe/safe-advanced-scrum-master.md",
    "title": "SAFe Advanced Scrum Master (SASM)"
  },
  {
    "path": "08-templates-and-toolkit/sprint-planning-agenda.md",
    "title": "Sprint Planning Agenda (Copy-Paste Template)"
  },
  {
    "path": "08-templates-and-toolkit/daily-scrum-formats.md",
    "title": "Daily Scrum Formats Beyond the Three Questions"
  },
  {
    "path": "08-templates-and-toolkit/retrospective-formats.md",
    "title": "Retrospective Formats"
  },
  {
    "path": "08-templates-and-toolkit/definition-of-done-checklist.md",
    "title": "Definition of Done Checklist"
  },
  {
    "path": "08-templates-and-toolkit/raci-and-stakeholder-map.md",
    "title": "RACI Matrix and Stakeholder Map for a Scrum Context"
  },
  {
    "path": "08-templates-and-toolkit/one-on-one-question-bank.md",
    "title": "1:1 Question Bank for Scrum Masters"
  },
  {
    "path": "09-interview-prep/scrum-master-interview-questions.md",
    "title": "Scrum Master Interview Questions"
  },
  {
    "path": "10-glossary.md",
    "title": "Glossary"
  }
];
